### ISSUE TITLE
Filter als Modul per Include-Element klappt nicht

### ISSUE THREAD

**Issue by psren** [MetaModels/filter_tags#11]
Wenn ich den Filter per CE-Erstelle klappt alles.

Wenn ich ihn per Modul erstelle und per IncludeElement einbinde dann klappt es nicht.
(Es wird nur "Alle Filter zusrücksetzen" angezeigt)

**Comment by xantippe** [comment]
@psren Verhalten noch aktuell?

**Comment by psren** [comment]
Kann ich kommende Woche nochmals testen

**Comment by xantippe** [comment]
das wäre super...

**Comment by xantippe** [comment]
und?

**Comment by psren** [comment]
Scheint inzwischen zu funktionieren.
