### ISSUE TITLE
URL value separator "," %2C

### ISSUE THREAD

**Issue by Aybee** [MetaModels/filter_tags#13]
Beim multiselect werden mehrere Werte in der URL mit einem Komma getrennt "%2C". Das finde ich nicht so schön. Hat das technische Gründe und muss deshalb so sein?

Ich fände einen Trennstrich dort z.B. besser.
```
http://example.org/products/apples%2Cpears.html
http://example.org/products/apples-pears.html
http://example.org/products/apples_pears.html
http://example.org/products/apples.pears.html
http://example.org/products/apples~pears.html
```

**Comment by discordier** [comment]
Das ist leider nicht moeglich, da die von dir genannten Moeglichkeiten innerhalb eines aliases vorkommen koennen und somit das System die tags anschliessend nicht mehr trennen koennte.

Es hat somit technische Gruende.

**Comment by Aybee** [comment]
Ok, danke. Schade irgendwie. Eine Idee wäre noch, einen von den Trennern bei der Aliaserzeugung auszuschließen, also z.B. "_". Ein "_" würde dann beim Alias in eine "-" geändert und wäre damit frei zur Trennung der Tags.

**Comment by discordier** [comment]
Wie meinen?

**Comment by Aybee** [comment]
Ich habe die Formatierung oben geändert, vielleicht wird jetzt deutlich, was ich meine.
vorher:
Mein_Name => mein_name
nachher:
Mein_Name => mein-name

Wenn `_` im Alias nicht mehr vorkommen würde, dann wäre er frei um ihn als Trenner zu benutzen.

**Comment by discordier** [comment]
Damit verhalten wir uns dann aber anders als alle anderen Stellen in Contao die aliase verwenden, denn dort sind "_" im alias erlaubt... Ich denke nicht, dass wir hiervon abweisen sollten, da dann alle Extension- und Template Ersteller dies bei sich reflektieren myssten. 
Das ist definitiv ein bc-break.

@tim-bec, @stefanheimes @MacKP eure Meinungen?

**Comment by MacKP** [comment]
Ich sehe das wie @discordier. Vor allem sind Abweichungen von Contao immer unpraktisch, da das ein erwartetes Verhalten ist. Wenn, dann sollte dieses Feature also im Contao Core kommen (da kann man dann ja ein Ticket zu machen).

Viele Grüße

**Comment by discordier** [comment]
Im core wird dies wohl aber nicht als "verbotenes" Zeichen deklariert werden, da etliche ja gerne "_" in aliasen haben wollen. Zumal es im core keine "multiplen" get parameter gibt sondern nur einen alias in der URL.

**Comment by Aybee** [comment]
Ja, ich dachte auch nicht daran das Core-Verhalten zu verändern, dachte das könnte man nur bei den Aliasen für den Multiselect patchen. Mit nem Slash, das wird dann wahrscheinlich auch nicht gehen?

Aber ok, ich habe mir gerade nochmal die URLs von Amazon angesehen, das ist ja ganz schlimm, da kann der Kunde wohl auch mit nem `%2C` leben.

**Comment by Aybee** [comment]
Ja. 

Ist halt nicht so schön, aber wenn's nicht anders geht... Ich habe jetzt schon länger nichts mehr mit MM gemacht.
