### ISSUE TITLE
Remove the re-declaration of fields `tl_metamodel_filtersetting.onlyused` and `tl_metamodel_filtersetting.onlypossible` 

### ISSUE THREAD

**Issue by cliffparnitzky** [MetaModels/filter_tags#15]
Remove the declaration of the fields `tl_metamodel_filtersetting.onlyused` and `tl_metamodel_filtersetting.onlypossible` in the DCA because they are already part of the core. The re-declaration will overwrite the core definition, which should only be extended.

**Comment by zonky2** [comment]
... and delete both fields at sql declaration => https://github.com/MetaModels/filter_tags/blob/master/contao/config/database.sql#L18-L19

**Comment by zonky2** [comment]
o.k. I change the declaration to
```
`$GLOBALS['TL_DCA']['tl_metamodel_filtersetting']['metapalettes']['tags extends _attribute_']['+fefilter'][] =
    'onlyused';
```
and works fine

**Comment by cliffparnitzky** [comment]
Okay, please, could you sum up, what has to be done?

**Comment by zonky2** [comment]
@cliffparnitzky pls test my PR https://github.com/zonky2/filter_tags/tree/Hotfix_%2315_remove_re-declaration_fields

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cliffparnitzky could you please have a final look at this and tell if your issue has been resolved?
