### ISSUE TITLE
Frontend filter tags processes only the first selected option if multiple options are selected

### ISSUE THREAD

**Issue by HaraldHubinger** [MetaModels/filter_tags#24]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/filter_tags/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.2.15      |                                  |
| Contao version:                     |   4.4.35       |                                  |
| MetaModels version core:            | 2.1.0@dev         |    6a8b3f                    |
| MetaModels version attribute:       | 2.1.0@dev         |    c4b7ad                              |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      | see below        |                                  |
| DCG version:                        |   dev-feature/contao4-release as 2.1.0       |      b5e684       |

        "metamodels/core": "^2.1.0@dev",
        "metamodels/attribute_alias": "^2.1.0@dev",
        "metamodels/attribute_checkbox": "^2.1.0@dev",
        "metamodels/attribute_combinedvalues": "^2.1.0@dev",
        "metamodels/attribute_decimal": "^2.1.0@dev",
        "metamodels/attribute_file": "^2.1.0@dev",
        "metamodels/attribute_longtext": "^2.1.0@dev",
        "metamodels/attribute_numeric": "^2.1.0@dev",
        "metamodels/attribute_select": "^2.1.0@dev",
        "metamodels/attribute_tabletext": "^2.1.0@dev",
        "metamodels/attribute_tags": "^2.1.0@dev",
        "metamodels/attribute_text": "^2.1.0@dev",
        "metamodels/filter_fromto": "^2.1.0@dev",
        "metamodels/filter_select": "^2.1.0@dev",
        "metamodels/filter_tags": "^2.1.0@dev",
        "metamodels/filter_text": "^2.1.0@dev"

## Issue description

MM-Frontend Filter Tags filters only for the first selected option, even if multiple options are selected. Also the frontend filter widget shows only the first selection after reload. The behaviour has been observed in a migrated Contao 3.5 / MM 2.0 and then reproduced on a brand-new and clean MM install as described above.

The reason seems to lie in the processing of the filter URL with is oft the form
filterparm/{list_of_ids} whereby {list_of_ids} is double URL-encoded. For example a selection of ids [1,2] resolves to http://fttest.localhost/seite/children/1%252C2.html.

MM filter tags seems to process this filterUrl only single decoded instead of double-decoded, as can be seen for example by doing a var_dump($arrFilterUrl) in MetaModels\FilterTagsBundle\FilterSetting\Tags on line 58, which returns a single encoded value
'children' => 
    array (size=1)
      0 => string '1%2C2'
instead of a comma separated list.
If you enter a URL with single encoded parameters manually you get the wanted result (in my example http://fttest.localhost/seite/children/1%2C2.html).

In the above mentioned migrated project I also observed in one of my own extensions that \Input::get() of a double-encoded URL-Parameter returns a single enccded value whereas the same code in Contao 3.5 returned the list of ids as expected.

Unfortunately I don't know enough about MM to file a pull request for this.

**Comment by zonky2** [comment]
related with https://github.com/MetaModels/core/issues/1282 ?

**Comment by discordier** [comment]
Should be fixed with the new filter url builder and d0e6023025a82b5d948265e0ca6f128f48d86026.
Could you test?

**Comment by zonky2** [comment]
testet - works fine
