### ISSUE TITLE
Support for Alias

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/filter_tags#26]
It's possible to add the alias and translatedalias as well to the list of supported attributes? @discordier @zonky2 

We have the text attribute allready in the list, so the alias should not be a problem.

**Comment by zonky2** [comment]
I don't see any problem with aliases... with translated alias... Hmm??

**Comment by discordier** [comment]
If testing works out ok, no problem to add - if not, then not.

**Comment by zonky2** [comment]
Add in MM 2.2
