### ISSUE TITLE
Feature: Add alias

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/filter_tags#29]
Can we add support for the alias attribute? Alias ist the same as text and better for the urls. 

See: https://github.com/MetaModels/filter_tags/blob/master/src/FilterSetting/TagsFilterSettingTypeFactory.php#L59

**Comment by zonky2** [comment]
@stefanheimes add new features als MR in MM 2.2

**Comment by zonky2** [comment]
Addes irgendwann https://github.com/MetaModels/filter_tags/blob/5e4f64774597b6ff6377a79e285c6aa2d43519ef/src/FilterSetting/TagsFilterSettingTypeFactory.php#L61
