### ISSUE TITLE
[TNG] FR: Für Filter Mehrfachauswahl die Option zum Filter überschreiben auch mehrfach

### ISSUE THREAD

**Issue by xantippe** [MetaModels/filter_tags#9]
Hallo,

beim Filter "Einfache Abfrage" kann man im CE MetaModel-List den Filter mit "Filtereinstellungen überschreiben" fest setzen...

... es wäre schön, wenn bei dem Filter Mehrfachauswahl, "Filtereinstellungen überschreiben" analog auch eine Mehrfachauswahl zulassen würde.

siehe https://community.contao.org/de/showthread.php?52473-Frage-zu-Filter-und-quot-Filtereinstellungen-%FCberschreiben-quot-im-CE-MetaModel-Liste&p=338493#post338493

Dank!

**Comment by psren** [comment]
:+1:

**Comment by discordier** [comment]
Wie soll die denn widgetmaessig aussehen?
Das grosse Problem was wir hier haben, sowas kann der MCW nicht darstellen.

Wir geben hier ja nur eine select box an, bei dem entsprechenden Filter mysste nun aber ein item picker erscheinen.

Man muss hierzu also ein vollkommen neues widget schreiben, die Seite von MetaModels ist dann piece of cake, aber das Konfigurationswidget, das wird eklig.

**Comment by xantippe** [comment]
hmmm... :-(

**Comment by xantippe** [comment]
Beim Überscheiben im CE-MM-Liste gibt es ein Select für die Auswahl - warum nicht ein Multi-Select?

**Comment by discordier** [comment]
Platzprobleme?

**Comment by xantippe** [comment]
sollte doch machbar sein - in Isotope gehts doch auch,,,

![shot46](https://cloud.githubusercontent.com/assets/1045318/12191473/b19b360a-b5d5-11e5-8853-b2d7755205b2.jpg)

und ein Designpreis will ich nicht gewinnen ;-)

**Comment by xantippe** [comment]
oder in den "neuen" Conditions
![shot48](https://cloud.githubusercontent.com/assets/1045318/12193404/5173fdb2-b5e8-11e5-946e-a733eb59a823.jpg)

**Comment by MacKP** [comment]
+1 (brauch man gar nicht bei isotope suche. Haben wir im MM auch schon drinn *g*)

**Comment by xantippe** [comment]
gerade nochmal angesehen... also wenn da kein Platz ist...

![shot51](https://cloud.githubusercontent.com/assets/1045318/12195778/1647de40-b5fa-11e5-9835-c71cd86a3d6a.jpg)

**Comment by xantippe** [comment]
siehe auch
https://community.contao.org/de/showthread.php?60354-MM-Tag-Filter-mit-mehreren-Auswahlm%F6glichkeiten

**Comment by xantippe** [comment]
... habe das nochmal ausprobiert:

zwei Anpassungen:
in https://github.com/MetaModels/core/blob/master/src/MetaModels/Widgets/SubDcaWidget.php#L299
neue Zeile ```$arrField['eval']['multiple']  = true;```

https://github.com/MetaModels/attribute_select/blob/master/src/MetaModels/Filter/Rules/FilterRuleSelect.php#L62
geändert in
```
$values = $this->objAttribute->convertValuesToValueIds(is_array($this->value) ? $this->value : explode(',', $this->value));
```

Ergebnis (nicht hübsch, aber geht)
![shot52](https://cloud.githubusercontent.com/assets/1045318/12197053/f2b4fe86-b603-11e5-9569-27ca3d6dbc70.jpg)
:::::::::::::::
![shot53](https://cloud.githubusercontent.com/assets/1045318/12197058/fa552ddc-b603-11e5-8a01-080f97bdd7b3.jpg)

**Comment by xantippe** [comment]
@discordier PR daraus machen?

**Comment by discordier** [comment]
Kannst du machen, aber bitte nimm auch mal so "grosse" Werte wie oben dein "Certified Scrum Master mit ....." und schau dir dann an ob das widget noch passt.
Allgemein bin ich der Thematik ja aufgeschlossen, aber es muss eben auch funktionieren.

**Comment by xantippe** [comment]
nun ja... unter normalen Umständen passt das schon - bei extremen Eingaben gibt es natürlich Probleme...

![shot54](https://cloud.githubusercontent.com/assets/1045318/12207704/76427c12-b648-11e5-839e-006ff1b92d0f.jpg)

![shot55](https://cloud.githubusercontent.com/assets/1045318/12207708/7a5ddf58-b648-11e5-83a3-224b58ecde95.jpg)

das liegt aber eher am Choosen-Modul und würde auch bei Contao-Core auftreten

sobald der Eintrag getrennt werden kann, sieht die Sache schon besser aus

![shot56](https://cloud.githubusercontent.com/assets/1045318/12207731/9ee249fe-b648-11e5-9ca3-ab8f9d381e6c.jpg)

**Comment by xantippe** [comment]
sorry und Kommando zurück - geht so leider doch nicht :-(

nach Durchsicht mit bzw. von xtra fiel uns/mir auf die Füße, dass das so mit dem Attribut Select ganz gut funktioniert - das ist aber auch eher "Zufall"...

ergo: hier muss eine saubere Implementierung her...

Kleiner Test am Rande - mehrfache "statische Parameter" werden anscheinend nicht zum CE durchgereicht :-(

![shot58](https://cloud.githubusercontent.com/assets/1045318/12223907/2c593a6c-b7e4-11e5-9762-292aed4440f4.jpg)

![shot59](https://cloud.githubusercontent.com/assets/1045318/12223910/34e54cde-b7e4-11e5-9c71-c6d61741fc55.jpg)

**Comment by xantippe** [comment]
Tipp von xtra: URL-Parameter unterschiedlich benennen

=> und dann gehts:

![shot60](https://cloud.githubusercontent.com/assets/1045318/12234714/394a37ea-b86f-11e5-99b1-d53570526e5f.jpg)


![shot61](https://cloud.githubusercontent.com/assets/1045318/12234722/3dc6db20-b86f-11e5-99d5-de9caa013667.jpg)

**Comment by xantippe** [comment]
siehe https://github.com/MetaModels/core/issues/659
